---
- name: My Test Playbook
  hosts: webservers
  become: true
  tasks:

  - name: Install multiple packages
    yum:
      name: ['git', 'make', 'gcc', 'wget', 'telnet', 'mysql', 'tree', 'which', 'docker']
      state: installed
