---
- name: my test playbook
  hosts: webservers
  become: true
  
  tasks:
  - name: stop service
    service:
      name: httpd
      state: stopped


  - name: uninstall httpd
    yum:
      name: httpd
      state: removed

